from manim import *

class Scene28(Scene):
    def construct(self):
        text_solution = Text("Solution", font_size=100, color=GOLD)
        self.play(Write(text_solution))
        self.wait(0.5)
        self.play(FadeOut(text_solution))
        text_step_1 = MathTex(r"1. \text{ Alice choose a prime } p \in [2..n^3]", font_size=45, color=BLUE)
        text_step_1.shift(UP*3)
        self.play(Write(text_step_1), run_time=5)
        self.wait(1)
        text_step_2 = MathTex(r"2. \text{ Alice computes } a \bmod p" , font_size=45, color=BLUE)
        text_step_2.next_to(text_step_1, DOWN)
        text_step_2.shift(DOWN*0.5)
        self.play(Write(text_step_2), run_time=2)
        self.wait(0.5)
        text_step_3 = MathTex(r"3. \text{ Alice sends } a \bmod p \text{ and } p \text{ to Bob}", font_size=45, color=BLUE)
        text_step_3.next_to(text_step_2, DOWN)
        text_step_3.shift(DOWN*0.5)
        self.play(Write(text_step_3), run_time=3)
        self.wait(0.5)
        text_step_4 = MathTex(r"4. \text{ Bob computes } b \bmod p }", font_size=45, color=BLUE)
        text_step_4.next_to(text_step_3, DOWN)
        text_step_4.shift(DOWN*0.5)
        self.play(Write(text_step_4), run_time=3.3)
        self.wait(0.5)
        text_step_5 = MathTex(r"5. \text{ If } a \bmod p = b \bmod p \text{, Bob concludes equality.}", font_size=45, color=BLUE)
        text_step_5.next_to(text_step_4, DOWN)
        text_step_5.shift(DOWN*0.5)
        self.play(Write(text_step_5), run_time=5.2)
        self.wait(0.5)
        text_step_6 = MathTex(r"6. \text{ If } a \bmod p \neq b \bmod p \text{, Bob concludes inequality.}", font_size=45, color=BLUE)
        text_step_6.next_to(text_step_5, DOWN)
        text_step_6.shift(DOWN*0.5)
        self.play(Write(text_step_6), run_time=5.5)
        self.wait(2)